### ISSUE TITLE
Game Center Achievement completion banner not showing

### ISSUE THREAD

**Issue by ghost** [nihalahmed/GameCenterManager#10]
I think they displayed in the beginning but somehow they don't show up anymore.

reportedAchievement is called and the achievement shows up in Game Center.
shouldDisplayNotification:YES is used.

Any other idea what could be wrong?

Is it possible that resetted achievements don't popup anymore?

**Comment by Bilalmirza** [comment]
Notification banner don't appear if the achievement is in a group. Is there a fix for it?
