### ISSUE TITLE
Current version apparently not compiling on Mac OS?

### ISSUE THREAD

**Issue by jcmendez** [nihalahmed/GameCenterManager#14]
I downloaded, and can build for iOS no problem.  When building for OS X, I'm getting errors regarding `UIViewController` not being defined.

I added to the headers on Mac side
 
    #if !TARGET_OS_IPHONE
    @compatibility_alias UIViewController NSViewController;
    #endif

and also wrapped the methods that don't compile... however, still I don't get the Mac OS version to run 

    diff --git a/GC Manager/GameCenterManager.h b/GC Manager/GameCenterManager.h
    index a2ecd467d56b05cef8f23593cf642f8fa6dea82d..9df27798229afb462f3ef4a2d95e689cbe756c66 100755
    --- a/GC Manager/GameCenterManager.h	
    +++ b/GC Manager/GameCenterManager.h	
    @@ -38,8 +38,6 @@
     #import "NSDataAES256.h"
 
 
    -
    -
     /// Leaderboard sort order. Use this value when submitting new leaderboard scores. This value should match the value set in iTunes Connect for the speicifed leaderboard.
     typedef enum GameCenterSortOrder {
         /// Scores are sorted highest to lowest. Higher scores are on the top of the leaderboard
    @@ -156,7 +154,7 @@ typedef NSInteger GCMErrorCode;
 
 
 
    -
    +#if TARGET_OS_IPHONE
     /// Presents the GameCenter Achievements ViewController over the specified ViewController. Dismissal and delegation is handled by GameCenterManager.
     - (void)presentAchievementsOnViewController:(UIViewController *)viewController;
 
    @@ -165,7 +163,7 @@ typedef NSInteger GCMErrorCode;
 
     /// Presents the GameCenter Challenges ViewController over the specified ViewController. Dismissal and delegation is handled by GameCenterManager.
     - (void)presentChallengesOnViewController:(UIViewController *)viewController;
    -
    +#endif
 
 
 
    diff --git a/GC Manager/GameCenterManager.m b/GC Manager/GameCenterManager.m
    index df357268a5ddd75cd0efe0810a44927202d2149e..669310a39209d7635ad4963874c4f0edad80e34b 100755
    --- a/GC Manager/GameCenterManager.m	
    +++ b/GC Manager/GameCenterManager.m	
    @@ -930,6 +930,8 @@
     //------------------------------------------------------------------------------------------------------------//
     #pragma mark - Presenting GameKit Controllers
 
    +#if TARGET_OS_IPHONE
    +
     - (void)presentAchievementsOnViewController:(UIViewController *)viewController {
         GKGameCenterViewController *achievementsViewController = [[GKGameCenterViewController alloc] init];
         achievementsViewController.viewState = GKGameCenterViewControllerStateAchievements;
    @@ -955,6 +957,8 @@
         [gameCenterViewController dismissViewControllerAnimated:YES completion:nil];
     }
 
    +#endif
    +
     //------------------------------------------------------------------------------------------------------------//
     //------- Resetting Data -------------------------------------------------------------------------------------//
     //------------------------------------------------------------------------------------------------------------//

**Comment by flexgames** [comment]
Same error here.
