### ISSUE TITLE
Achievements not syncing

### ISSUE THREAD

**Issue by Xtreeemz** [nihalahmed/GameCenterManager#28]
Trying to sync achievements saved from offline play. Doesn't work as reportSavedScoresAndAchievements is not called in GameCenterManager's init method. This appears to happen because checkGameCenterAvailability always returns false on application startup (which makes sense, because GC hasn't had time to authenticate yet.

Relevant code:

if (self) {
        BOOL gameCenterAvailable = [self checkGameCenterAvailability];
        
        if (gameCenterAvailable) {
            // Set GameCenter as available
            [self setIsGameCenterAvailable:YES];
            
            if (![[NSUserDefaults standardUserDefaults] boolForKey:[@"scoresSynced" stringByAppendingString:[self localPlayerId]]]
                || ![[NSUserDefaults standardUserDefaults] boolForKey:[@"achievementsSynced" stringByAppendingString:[self localPlayerId]]])
                [self syncGameCenter];
            else
                [self reportSavedScoresAndAchievements];
        } else
            [self setIsGameCenterAvailable:NO];
    }

**Comment by danoli3** [comment]
Possible causes: You didn't have achievements or leaderboards setup. Not having one of either will cause this issue.
Make sure to add both for Game Center Manager to work.

**Comment by Sam-Spencer** [comment]
Going to close this issue unless it continues to persist (in that case, comment here and it can be reopened).
