### ISSUE TITLE
GCM v5.3 build for Mac fails on Xcode 6.1.1 on first compile

### ISSUE THREAD

**Issue by flexgames** [nihalahmed/GameCenterManager#31]
Title pretty much says it all. I'm having a heck of a time getting GCM for Mac to work, so I decided to go back to the original 5.3 project. When I try to compile it with no modifications there are 11 errors. 

![screen shot 2014-12-09 at 5 50 59 pm](https://cloud.githubusercontent.com/assets/2111634/5369665/1e07f6fc-7fcc-11e4-8318-ac7d07f851d0.png)

Any suggestions?

**Comment by flexgames** [comment]
Is this project still being developed? It's been over a year since 5.3 release? Beuller?

**Comment by Sam-Spencer** [comment]
Hi there @flexgames! You're right! It has been a long time since an update to this project. Over the next few days I will be pushing up updates to the project and will update you on the project status as things changes. Thanks for letting me know!

**Comment by flexgames** [comment]
Sam,

Music to my eyes!

Thanks so much  - I can’t wait - I have a game complete except for GCM functionality on Mac, so this would be fantastic.

Joe
