### ISSUE TITLE
Player is not signed into GameCenter...

### ISSUE THREAD

**Issue by flexgames** [nihalahmed/GameCenterManager#32]
Thank you Sam for updating GCM for 10.10 compatibility.

After downloading a fresh copy of it, and changing the com.xxxxx.GameCenterManager.Mac to my domain, and creating the App ID on developer.apple.com, I was able to successfully run the GCM demo under the Mac side. 

However every run I get:
"Player is not signed into GameCenter, has declined to sign into GameCenter, or GameKit had an issue validating this game / app"

I am logged in and I have the sandbox enabled. Any suggestions on why it says I'm not signed in or how to troubleshoot?

![screen shot 2015-01-18 at 11 13 39 am](https://cloud.githubusercontent.com/assets/2111634/5793711/16d0a7e8-9f03-11e4-9954-0a146169f7f5.png)
![screen shot 2015-01-18 at 11 13 46 am](https://cloud.githubusercontent.com/assets/2111634/5793712/16f1c4f0-9f03-11e4-979b-ffc0ee844525.png)
![screen shot 2015-01-18 at 11 14 39 am](https://cloud.githubusercontent.com/assets/2111634/5793715/3781ea6a-9f03-11e4-92f8-7b1d82fca489.png)

Thanks.

**Comment by flexgames** [comment]
Is anyone else having this issue? Any suggestions on a workaround? It's been open for 6+ months. Thanks.

**Comment by flexgames** [comment]
I just pulled the latest and running on OS X 10.11.1 upon first launch I am getting:

`2015-11-10 08:14:10.190 GameCenterManager Mac[18660:4035618] Could not get services from gamed. Please file a radar including GameKit logs, and any gamed crash logs. ERROR Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.gamed.osx was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.gamed.osx was invalidated.}`

**Comment by danoli3** [comment]
I wasn't having this issue with my project.. I'll see, maybe it's an issue with Sandbox mode.

**Comment by danoli3** [comment]
I can't actually set Sandbox mode like you did.

<img width="268" alt="screen shot 2015-11-16 at 10 57 34 pm" src="https://cloud.githubusercontent.com/assets/830748/11181728/e013284e-8cb8-11e5-8ece-7e7284683574.png">

Have you opened up the Game Center App from Apple and successfully logged in?

**Comment by flexgames** [comment]
Yes I'm logged in via GC. Other games (Hero Academy) are using GC fine on this Mac.

Just to confirm, you're logged in via GC, on OS X 10.11.x and are able to successfully log into GCM Mac, when you run it?

**Comment by danoli3** [comment]
Yeah working fine. Try this branch 
https://github.com/danoli3/GameCenterManager/tree/Fix/OSX-SyncFix

It fixes up permissions in the example project... maybe was something left in there.

**Comment by danoli3** [comment]
Oh wow! Okay, Under AppSanbox yeah:
```
Could not get services from gamed. 
Please file a radar including GameKit logs, and any gamed crash logs. 
ERROR Error Domain=NSCocoaErrorDomain Code=4099 
"The connection to service named com.apple.gamed.osx was invalidated." U
serInfo={NSDebugDescription=The connection to service named com.apple.gamed.osx was invalidated.}
```

**Comment by flexgames** [comment]
Thanks. So you're only seeing this issue with sandbox enabled?

**Comment by danoli3** [comment]
Yeah it only occurs with App Sandbox on. 

I'm thinking its some sort of Apple URL types issue.

As I can confirm I definitely have the entitlements to server/client set to YES.

**Comment by flexgames** [comment]
Can you remind me how to turn App Sandbox off on OS X? I am googling for it and cannot seem to location the switch!  Thanks in advance. I want to test the same thing (with it off).

**Comment by danoli3** [comment]
Oh it's in Xcode within your project, under your Target, General tab, with all the buttons to switch things off like Game Center, iCloud etc. App Sandbox is at the top.

**Comment by danoli3** [comment]
This user was having the same issue in Yosemite: http://stackoverflow.com/questions/29295423/osx-game-center-couldnt-communicate-with-a-helper-application

There has to be a solution as games for OSX are submitted all the time with Game Center. I wonder what the issue is.

**Comment by danoli3** [comment]
Oh yeah and with the Example Mac application in this repo, once you toggle "AppSandbox" the same thing happens.

**Comment by danoli3** [comment]
I think I figured it out.

**Comment by flexgames** [comment]
great!

**Comment by danoli3** [comment]
https://github.com/nihalahmed/GameCenterManager/pull/58

Add this key to the entitlements of the OSX App:

> com.apple.developer.game-center

BOOLEAN = YES
(As well as the client/server ones).

**Comment by danoli3** [comment]
@flexgames yay!
