### ISSUE TITLE
Cocos2D-swift

### ISSUE THREAD

**Issue by FlappyHeart** [nihalahmed/GameCenterManager#33]
I am new to cocos2D, I just don't know how to show leaderboard in my code because I just used some ccb files as scenes. There is no viewControllers in my code. Any help will be great appreciated!

**Comment by FlappyHeart** [comment]
I mean this method:
`[[GameCenterManager sharedManager] presentLeaderboardsOnViewController:self];`

What should I use to instead of self cause I want to show leaderboard in a scene which inherit from CCNode

**Comment by ckjbeos** [comment]
hi,

i use this :
 /**** connexion au gameCenter ****/
- (void)gameCenterManager:(GameCenterManager *)manager authenticateUser:(UIViewController *)gameCenterLoginController
{
    AppDelegate     *app = (AppDelegate*) [[UIApplication sharedApplication] delegate];
        
    // afficher la connexion au gamecenter
    [app.navController presentViewController:gameCenterLoginController animated:YES completion:^{ }];
}

best regards,
Cedric - Pixs'n Bits

**Comment by FlappyHeart** [comment]
@ckjbeos  Thanks for your reply! But I still don't know how to use this method in my FooScene.m file.

**Comment by ckjbeos** [comment]
@FlappyHeart, i add this into appDelegeate ;)
not use it into cocosScene
add this into appDelegeate and call from Cocos Scene after ;) (that's work)

**Comment by FlappyHeart** [comment]
@ckjbeos  Ha! It's awesome! I got this, you're so smart!  I'll try this. Thanks so much for your answer!

**Comment by ckjbeos** [comment]
@FlappyHeart happy to see it help you :)
if you have time, just try our app :) binary game named : 10101100

**Comment by FlappyHeart** [comment]
@ckjbeos  Where can I find your app? I am so glad to have a try! Is it published on app store?

**Comment by ckjbeos** [comment]
hi @FlappyHeart,
Yes our apps are on app store : https://itunes.apple.com/fr/artist/pixsn-bits/id332102344
Thanks :)
Best regards,
Cedric - Pixs'n Bits

**Comment by FlappyHeart** [comment]
@ckjbeos   How about use just one font style like Helivetica everywhere in the game?  Otherwise, the background animation looks wonderful, and the game is amazing even a little hard for me, great job!

**Comment by ckjbeos** [comment]
@FlappyHeart i try in first time to use the same ;)
but in how to i need to get a fixed space style font (display binary with value in same column), but this fixed is not fun in entire game.
