### ISSUE TITLE
Ability to login again if user decline login first time ?

### ISSUE THREAD

**Issue by linked67** [nihalahmed/GameCenterManager#34]
Hi,

If the user cancel the login controller, every other time i call:

    [[GameCenterManager sharedManager] presentLeaderboardsOnViewController:self];

It only show a alert view that say user is not signed in.
Is there a way to display the login again ?

It's on IOS.

**Comment by dakikifr** [comment]
After 3 cancel of the login sequence in your application, the login viewcontroller won't be proposed again.
As the Apple documentation states, the user should be directed to the GameCenter application to sign in manually.
