### ISSUE TITLE
Delegates called too often gameCenterManager:availabilityChanged:

### ISSUE THREAD

**Issue by RoLYroLLs** [nihalahmed/GameCenterManager#38]
I've notice that the delegate method `gameCenterManager:availabilityChanged: ` gets called after a call to `checkGameCenterAvailability`, no matter if the true status changed or not, which gets called on `init`, `syncGameCenter`, `saveAndReportScore:leaderboard:sortOrder:`, `saveAndReportAchievement:percentComplete:shouldDisplayNotification:`, and `getChallengesWithCompletion:`.

While this doesn't seem too bad, I think it should not be called UNLESS something actually changed. If there are reason that it should remain this way, please enlighten me. I love to learn reasons for things like this that I may not have foreseen.

Otherwise, I invite anyone to help optimized this as I will try to do so as well.

Thanks.

**Comment by danoli3** [comment]
This is a huge issue. Thanks @RoLYroLLs for the fix
