### ISSUE TITLE
Scores greater than 2147483647 not saved on Game Center.

### ISSUE THREAD

**Issue by sakisdog** [nihalahmed/GameCenterManager#42]
Scores greater than max int value (2147483647) not being saved on Game Center. I think the error is located in - (void)saveAndReportScore:(int)score leaderboard:(NSString *)identifier sortOrder:(GameCenterSortOrder)order method. score should be long long and not int.

**Comment by danoli3** [comment]
True! Should not be int.

**Comment by danoli3** [comment]
@sakisdog I've posted a PR with the fix.

**Comment by danoli3** [comment]
@nihalahmed you still around mate? The other PR's are also good to merge. Tried them out.

**Comment by Sam-Spencer** [comment]
Commit b4d5c3c7f63c0500e9d992d8e5047793814a6dc7 fixes this issue.
