### ISSUE TITLE
Deprecated methods on iOS 9.0

### ISSUE THREAD

**Issue by txaidw** [nihalahmed/GameCenterManager#44]
Will this be updated for Xcode 7 and iOS 9? Thanks! :)

**Comment by ckjbeos** [comment]
Hi @txaidw have you some issue with XCode 7 and iOS 9 ?
don't upgrade at this time ;) but would like to know befaore do it !

Regards,
Cedric - Pixs'n Bits

**Comment by Bashta** [comment]
Ill give it a go tonight!

**Comment by txaidw** [comment]
Until now it appears to be working, login at least, but it has some deprecated methods
