### ISSUE TITLE
Game Center Multiplayer matches

### ISSUE THREAD

**Issue by Matsepura** [nihalahmed/GameCenterManager#45]
"In future updates, GameCenter Manager will make it easy to setup and run live Game Center Multiplayer matches." - when you planning to make it? Thank you for your work!=)

**Comment by Sam-Spencer** [comment]
Take a look at commit f88a6837880cb3c750430f3ada6a45d6c2a8add6. This should be exactly what you're looking for :tada:

**Comment by rjgdesign** [comment]
Awesome! How would I find local players only (on same wifi or bluetooth network)?

**Comment by Matsepura** [comment]
Great! Thanks!)

**Comment by Sam-Spencer** [comment]
Any reason this issue got reopened?

**Comment by Matsepura** [comment]
Just lag
