### ISSUE TITLE
saveAndReportAchievement error

### ISSUE THREAD

**Issue by Tozso78** [nihalahmed/GameCenterManager#48]
I use the saveAndReportAchievement method, but in the consol i got this message:

no bundle for bundleID: (null)

The gamecenter save the achievement progress, but no notification banner shoes up, it's works before IOS9.

Anyone can help me?
Ty

**Comment by danoli3** [comment]
iOS Bug. rdar://23149890

**Comment by Sam-Spencer** [comment]
Looks like this could be a bug in iOS, not GameCenterManager. Closing this issue unless it is found to be  otherwise.
