### ISSUE TITLE
saveAndReportScore with GameCenterSortOrderLowToHigh doesn't work

### ISSUE THREAD

**Issue by iversoft** [nihalahmed/GameCenterManager#75]
The first time you save a score (say 500), it pulls out the previous score and if there is none it uses 0 as a placeholder. Then it tests if your score is better. This works fine for high-to-low ordering, but for low-to-high ordering, the placeholder of 0 tests as the "better" score. So then it doesn't save your score, it saves 0 instead.

Seems like a pretty basic use case. The fact that it is handled wrong makes me leery of using this library...

**Comment by danoli3** [comment]
@iversoft nice find, should be an easy fix though... PR?

**Comment by ahmedrezik** [comment]
Does this issue still need fixing ?
