### ISSUE TITLE
Update to Game Center 2020 API changes for iOS 14

### ISSUE THREAD

**Issue by danoli3** [nihalahmed/GameCenterManager#78]
https://developer.apple.com/game-center/

https://developer.apple.com/documentation/gamekit/

**Comment by danoli3** [comment]
@Sam-Spencer happy to help with this if you make me collaborator, can't have PR's being around for years mate :) haha

**Comment by Sam-Spencer** [comment]
Your contributions to the repo have been fantastic! Unfortunately, I don't have admin access. Maybe @nihalahmed could add you? If not, I'll be happy to continue merging your PRs!

**Comment by danoli3** [comment]
Awesome yeah that will be great! Perfect I'll be looking at updating this later this week / next

**Comment by danoli3** [comment]
Okay sweet will make these changes

**Comment by danoli3** [comment]
Done done done
